resources:
  - postgres-dc.yaml
  - postgres-pvc.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - sonar-cm-config.yaml
  - sonar-deployment.yaml
  - sonar-pvc.yaml
  - sonar-route.yaml
  - sonar-service.yaml
  - sonar-job.yaml
  - sonar-job-cm.yaml
  - sonar-job-rb.yaml
  - sonar-job-sa.yaml